//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CON_RESP_TRIBUTARIA
    {
        public int PK_COD_CONT_RESP { get; set; }
        public string CONT_COD_RESP { get; set; }
        public string CONR_NOMBRE_RESP { get; set; }
        public Nullable<bool> CON_RES_ACTIVO { get; set; }
    }
}
