//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USUARIO
    {
        public int PK_ID_SYS_USUARIO { get; set; }
        public Nullable<int> SYS_USU_TIPOIDENTIFICACION { get; set; }
        public string SYS_USU_IDENTIFICACION { get; set; }
        public string SYS_USU_NOMBRE { get; set; }
        public string SYS_USU_APELLIDO { get; set; }
        public string SYS_USU_USERNAME { get; set; }
        public string SYS_USU_CLAVE { get; set; }
        public string PK_ID_GEN_PERFIL { get; set; }
        public string SYS_USU_CORREOUSUARIO { get; set; }
        public Nullable<bool> SYS_USU_ACTIVO { get; set; }
    }
}
